language: node_js
node_js:
  - "8.4"

branches:
  only:
    - master

before_script:
  - npm install -g gulp firebase-tools

script:
  - gulp

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"